name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name == 'push'
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.5.1
        with:
          version: latest
          install: true

      - name: Extract Docker metadata for main build
        id: meta
        uses: docker/metadata-action@v3.4.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=${{ github.event_name == 'push' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.6.1
        with:
          context: src/
          file: src/BlazeBin/Server/Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-to: type=gha, scope=${{github.repository}}
          cache-from: type=gha, scope=${{github.repository}}

  publish:
    #if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Sleep for 15 seconds
        run: sleep 5s
        shell: bash
      - name: Login to azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: deploy webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'blazebin'
          images: 'cisien/blazebin:main'
